"""empty message

Revision ID: 4c2e9062c94b
Revises: dbc763033006
Create Date: 2025-12-19 01:12:22.527423

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "4c2e9062c94b"
down_revision: str | Sequence[str] | None = "dbc763033006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
