"""Add meta_data column to workshop_items

Revision ID: add_meta_data
Revises: 725eac1c59a7
Create Date: 2025-01-24 15:05:00.000000

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "add_meta_data"
down_revision: str | Sequence[str] | None = "725eac1c59a7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("workshop_items", sa.Column("metadata", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workshop_items", "metadata")
    # ### end Alembic commands ###
