"""empty message

Revision ID: cb51acf259c6
Revises: e7246c856afa
Create Date: 2025-12-19 00:43:22.647209

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "cb51acf259c6"
down_revision: str | Sequence[str] | None = "e7246c856afa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workshop_items",
        sa.Column("file_size", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.alter_column(
        "workshop_items",
        "description",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "workshop_items",
        "description",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.drop_column("workshop_items", "file_size")
    # ### end Alembic commands ###
