"""empty message

Revision ID: dbc763033006
Revises: cb51acf259c6
Create Date: 2025-12-19 01:06:00.995309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbc763033006'
down_revision: Union[str, Sequence[str], None] = 'cb51acf259c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workshop_items', 'file_size',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               postgresql_using='file_size::integer',
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workshop_items', 'file_size',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               postgresql_using='file_size::text',
               nullable=True)
    # ### end Alembic commands ###
