"""empty message

Revision ID: dbc763033006
Revises: cb51acf259c6
Create Date: 2025-12-19 01:06:00.995309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbc763033006'
down_revision: Union[str, Sequence[str], None] = 'cb51acf259c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # PostgreSQL cannot always implicitly cast VARCHAR -> INTEGER, especially if
    # existing rows contain non-numeric strings. Use an explicit USING clause
    # that:
    # - maps NULL/empty to 0
    # - allows pure integers
    # - otherwise strips non-digits and casts (or falls back to 0)
    op.execute(
        """
        ALTER TABLE workshop_items
        ALTER COLUMN file_size TYPE INTEGER
        USING (
            CASE
                WHEN file_size IS NULL OR btrim(file_size) = '' THEN 0
                WHEN file_size ~ '^[0-9]+$' THEN file_size::integer
                ELSE COALESCE(NULLIF(regexp_replace(file_size, '[^0-9]', '', 'g'), '')::integer, 0)
            END
        )
        """
    )
    op.alter_column(
        'workshop_items',
        'file_size',
        existing_type=sa.Integer(),
        nullable=False,
        server_default=sa.text("0"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'workshop_items',
        'file_size',
        existing_type=sa.Integer(),
        nullable=True,
        server_default=None,
    )
    op.alter_column(
        'workshop_items',
        'file_size',
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(),
        nullable=True,
        postgresql_using='file_size::text',
    )
    # ### end Alembic commands ###
