"""Initial migration: create workshop_items table

Revision ID: e7246c856afa
Revises:
Create Date: 2025-12-19 00:00:22.746419

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e7246c856afa"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workshop_items",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("coverview_url", sa.String(), nullable=False),
        sa.Column("author", sa.String(), nullable=False),
        sa.Column("author_profile", sa.String(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("synced_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_workshop_items_author"), "workshop_items", ["author"], unique=False)
    op.create_index(op.f("ix_workshop_items_id"), "workshop_items", ["id"], unique=False)
    op.create_index(op.f("ix_workshop_items_title"), "workshop_items", ["title"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_workshop_items_title"), table_name="workshop_items")
    op.drop_index(op.f("ix_workshop_items_id"), table_name="workshop_items")
    op.drop_index(op.f("ix_workshop_items_author"), table_name="workshop_items")
    op.drop_table("workshop_items")
    # ### end Alembic commands ###
