"""empty message

Revision ID: f69e89ce9b69
Revises: 4c2e9062c94b
Create Date: 2025-12-19 01:27:42.909496

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f69e89ce9b69"
down_revision: Union[str, Sequence[str], None] = "4c2e9062c94b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("workshop_items", sa.Column("images", sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workshop_items", "images")
    # ### end Alembic commands ###
